[package]
name = "cmsis-dsp-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
cty = "0.2.2"

[build-dependencies]
bindgen = "0.71.1"
regex = "1.11.1"
reqwest = { version = "0.12.15", features = ["blocking", "rustls-tls"], default-features = false }
zip = "2.6.1"
